# Generated by Django 5.2.3 on 2025-11-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_days', models.PositiveIntegerField()),
                ('exclude_weekends', models.BooleanField(default=True, help_text='If checked, weekends will be excluded from leave calculation (only working days counted). If unchecked, all days including weekends will be counted.')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
