# Generated by Django 5.2.3 on 2025-11-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_employee_supervisor'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='gender_restriction',
            field=models.CharField(choices=[('both', 'Both Male and Female'), ('male', 'Male Only'), ('female', 'Female Only')], default='both', help_text='Specify which gender can apply for this leave type.', max_length=10),
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('leave_days', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('return_date', models.DateField()),
                ('reason', models.TextField()),
                ('delegation_accepted', models.BooleanField(default=False)),
                ('delegation_acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('delegatee_remarks', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('supervisor_approval', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True)),
                ('supervisor_comments', models.TextField(blank=True, null=True)),
                ('hr_approval_date', models.DateTimeField(blank=True, null=True)),
                ('hr_approval', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True)),
                ('hr_comments', models.TextField(blank=True, null=True)),
                ('ed_approval_date', models.DateTimeField(blank=True, null=True)),
                ('ed_approval', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True)),
                ('ed_comments', models.TextField(blank=True, null=True)),
                ('ed_approved', models.BooleanField(default=False)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegated_leaves', to='hr.employee')),
                ('delegatee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_duties', to='hr.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to='hr.employee')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('annual_entitlement', models.FloatField(default=0)),
                ('carried_forward_days', models.FloatField(default=0)),
                ('days_used', models.FloatField(default=0)),
                ('year', models.IntegerField(default=2025)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
            ],
            options={
                'verbose_name_plural': 'Leave Balances',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
