# Generated by Django 5.2.3 on 2025-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavetype_gender_restriction_leaveapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='submitted', max_length=20),
        ),
    ]
