# Generated by Django 5.2.3 on 2025-12-04 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_dependent_relationship'),
        ('leave', '0003_leaveapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='delegatee',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='delegated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_duties', to='hr.employee'),
        ),
    ]
