# Generated by Django 5.2.3 on 2025-12-06 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_remove_leaveapplication_delegatee_leavetype_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('leave_days', models.PositiveIntegerField()),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leaveapplication')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
