# Generated by Django 5.2.3 on 2025-12-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leaveevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
