# Generated by Django 5.2.3 on 2025-12-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_alter_leaveapplication_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'ordering': ['-created'], 'permissions': [('can_approve_leave', 'Can approve leave applications')]},
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('delegation_accepted', 'Delegation Accepted'), ('delegation_rejected', 'Delegation Rejected'), ('supervisor_approved', 'Supervisor Approved'), ('supervisor_rejected', 'Supervisor Rejected'), ('hr_approved', 'HR Approved'), ('hr_rejected', 'HR Rejected'), ('ed_approved', 'ED Approved'), ('ed_rejected', 'ED Rejected')], default='submitted', max_length=20),
        ),
    ]
