# Generated by Django 5.2.3 on 2025-12-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_leaveapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='supervisor_approval',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='supervisor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
