# Generated by Django 5.2.3 on 2025-12-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_remove_leaveapplication_supervisor_approval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='ed_approval_date',
            new_name='director_approval_date',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='ed_approved',
            new_name='director_approved',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='ed_comments',
            new_name='director_comments',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='ed_approval',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('delegation_accepted', 'Delegation Accepted'), ('delegation_rejected', 'Delegation Rejected'), ('supervisor_approved', 'Supervisor Approved'), ('supervisor_rejected', 'Supervisor Rejected'), ('hr_approved', 'HR Approved'), ('hr_rejected', 'HR Rejected'), ('director_approved', 'Director Approved'), ('director_rejected', 'Director Rejected')], default='submitted', max_length=20),
        ),
    ]
