# Generated by Django 5.2.3 on 2025-12-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_rename_ed_approval_date_leaveapplication_director_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'ordering': ['-created'], 'permissions': [('can_approve_leave', 'Can approve leave applications'), ('director_approve_leave', 'Can approve leave applications as Director')]},
        ),
    ]
