# Generated by Django 5.2.3 on 2025-12-26 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_employee_directorate'),
        ('leave', '0010_alter_leaveapplication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'ordering': ['-created'], 'permissions': [('can_approve_leave', 'Can approve leave applications'), ('director_approve_leave', 'Can approve leave applications as Director'), ('hr_approve_leave', 'Can approve leave applications as HR')]},
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='hr_approval',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_leave_approvals', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_leave_approvals', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='hr_approved',
            field=models.BooleanField(default=False),
        ),
    ]
