# Generated by Django 5.2.3 on 2026-08-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_alter_leaveapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveevent',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
