# Generated by Django 5.2.3 on 2025-10-21 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PRNCallIns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_option_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_option_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPRNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('system_status', models.BooleanField(default=True)),
                ('pay_request_status', models.BooleanField(default=False)),
                ('audit_completed_status', models.BooleanField(default=False)),
                ('served_status', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('banktxnid', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('payment_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_payment_option_id', to='payments.paymentoptions')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestCallbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ura_status', models.CharField(max_length=40)),
                ('mobilemoney_post_date', models.DateTimeField(blank=True, null=True)),
                ('mm_transaction_id', models.CharField(max_length=100)),
                ('ura_post_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('overall_status', models.CharField(max_length=20)),
                ('last_post_message', models.CharField(max_length=20)),
                ('internal_reference', models.CharField(max_length=20)),
                ('external_reference', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_prn_payment_request_callback', to='payments.applicationprns')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_transaction_id', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=12, null=True)),
                ('external_transaction_id', models.CharField(max_length=100)),
                ('return_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_request_status', models.BooleanField(default=False)),
                ('request_response', models.TextField(blank=True, null=True)),
                ('response_status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_prn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_prn_payment_request', to='payments.applicationprns')),
            ],
        ),
    ]
