# Generated by Django 5.2.3 on 2026-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationprns',
            old_name='bank',
            new_name='buildingName',
        ),
        migrations.RenameField(
            model_name='applicationprns',
            old_name='banktxnid',
            new_name='contactNo',
        ),
        migrations.RenameField(
            model_name='applicationprns',
            old_name='branch',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='audit_completed_status',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='pay_request_status',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='payment_option_id',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='prn',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='served_status',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='status',
        ),
        migrations.RemoveField(
            model_name='applicationprns',
            name='system_status',
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='assessmentDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='expiryDays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='localCouncil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='mobileMoneyNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='parish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='paymentPeriod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='paymentType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='plot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='referenceNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='srcSystem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='subCounty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='taxHead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='taxPayerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='taxSubHead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='tin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='tradeCentre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
