# Generated by Django 5.2.3 on 2026-02-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_bank_applicationprns_buildingname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('payment_tax_head', models.CharField(max_length=100)),
                ('available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('base_value', models.IntegerField()),
                ('base_value_currency', models.CharField(max_length=100, null=True)),
                ('tax_head_currency', models.CharField(max_length=100, null=True)),
                ('fees_per_unit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
