# Generated by Django 5.2.3 on 2026-02-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcode',
            name='fees_per_unit',
        ),
    ]
