# Generated by Django 5.2.3 on 2026-02-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_paymentcode_fees_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
