# Generated by Django 5.2.3 on 2026-02-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentoptions',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentoptions',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='paymentrequestcallbacks',
            name='prn',
        ),
        migrations.RemoveField(
            model_name='paymentrequests',
            name='related_prn',
        ),
        migrations.DeleteModel(
            name='PRNCallIns',
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='prn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='searchCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='statusCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='statusDesc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentOptions',
        ),
        migrations.DeleteModel(
            name='PaymentRequestCallbacks',
        ),
        migrations.DeleteModel(
            name='PaymentRequests',
        ),
    ]
