# Generated by Django 5.2.3 on 2026-02-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_paymentoptions_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationprns',
            name='referenceNo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
