# Generated by Django 5.2.3 on 2026-02-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_applicationprns_referenceno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationprns',
            name='referenceNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
