# Generated by Django 5.2.3 on 2026-02-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_applicationprns_referenceno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationprns',
            name='id',
        ),
        migrations.AddField(
            model_name='applicationprns',
            name='prn_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationprns',
            name='referenceNo',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
