# Generated by Django 5.2.3 on 2026-02-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_applicationprns_id_and_more'),
    ]

    operations = [
       
    ]
