# Generated by Django 5.2.3 on 2026-02-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_applicationprns_id_alter_applicationprns_referenceno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationPRNS',
        ),
    ]
