# Generated by Django 5.2.3 on 2026-02-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_delete_applicationprns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPRNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('assessmentDate', models.DateTimeField(blank=True, null=True)),
                ('paymentType', models.CharField(blank=True, max_length=100, null=True)),
                ('referenceNo', models.CharField(blank=True, max_length=100, null=True)),
                ('tin', models.CharField(blank=True, max_length=100, null=True)),
                ('srcSystem', models.CharField(blank=True, max_length=100, null=True)),
                ('taxHead', models.CharField(blank=True, max_length=100, null=True)),
                ('taxSubHead', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('taxPayerName', models.CharField(blank=True, max_length=100, null=True)),
                ('plot', models.CharField(blank=True, max_length=100, null=True)),
                ('buildingName', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('tradeCentre', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('subCounty', models.CharField(blank=True, max_length=100, null=True)),
                ('parish', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('localCouncil', models.CharField(blank=True, max_length=100, null=True)),
                ('contactNo', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentPeriod', models.CharField(blank=True, max_length=100, null=True)),
                ('expiryDays', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileMoneyNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileNo', models.CharField(blank=True, max_length=100, null=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('statusCode', models.CharField(blank=True, max_length=10, null=True)),
                ('statusDesc', models.CharField(blank=True, max_length=100, null=True)),
                ('searchCode', models.CharField(blank=True, max_length=100, null=True)),
                ('prn', models.CharField(blank=True, max_length=100, null=True)),
                ('prn_reconciled', models.BooleanField(default=False)),
            ],
        ),
    ]
