# Generated by Django 5.2.3 on 2026-03-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_applicationprns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationprns',
            options={'verbose_name': 'Application PRN', 'verbose_name_plural': 'Application PRNs'},
        ),
    ]
