# Generated by Django 5.2.3 on 2025-11-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0010_rename_post_address_institution_postal_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=100, unique=True)),
                ('application_type', models.CharField(choices=[('new', 'New'), ('renewal', 'Renewal')], default='new', max_length=100)),
                ('programme_level', models.CharField(choices=[('higher_education_certificate', 'Higher Education Certificate'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'Bachelors'), ('post_graduate_diploma', 'Post Graduate Diploma'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=100)),
                ('programme_name', models.CharField(max_length=255)),
                ('duration_semester', models.PositiveIntegerField()),
                ('campus', models.CharField(blank=True, max_length=255, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('programme_structure', models.FileField(blank=True, null=True, upload_to='programmes/')),
                ('letter_of_submission', models.FileField(blank=True, null=True, upload_to='programmes/')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='programme_accreditations', to='institutions.institution')),
            ],
        ),
    ]
