# Generated by Django 5.2.3 on 2025-11-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_rename_post_address_institution_postal_address'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeaccreditation',
            name='application_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='programmeaccreditation',
            name='institution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='programme_accreditations', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='programmeaccreditation',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
