# Generated by Django 5.2.3 on 2025-11-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_rename_post_address_institution_postal_address'),
        ('programmes', '0002_alter_programmeaccreditation_application_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('program_level', models.CharField(blank=True, choices=[('higher_education_certificate', 'Higher Education Certificate'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'Bachelors'), ('post_graduate_diploma', 'Post Graduate Diploma'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=255, null=True)),
                ('accreditation_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('application_type', models.CharField(choices=[('new', 'New'), ('renewal', 'Renewal')], default='new', max_length=100)),
                ('program_level', models.CharField(choices=[('higher_education_certificate', 'Higher Education Certificate'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'Bachelors'), ('post_graduate_diploma', 'Post Graduate Diploma'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=100)),
                ('program_name', models.CharField(max_length=255)),
                ('duration_semester', models.PositiveIntegerField()),
                ('campus', models.CharField(blank=True, max_length=255, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('program_structure', models.FileField(blank=True, null=True, upload_to='programmes/')),
                ('letter_of_submission', models.FileField(blank=True, null=True, upload_to='programmes/')),
                ('institution', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='programme_accreditations', to='institutions.institution')),
                ('program_to_renew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='programmes.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='program_accreditation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programmes.programaccreditation'),
        ),
        migrations.DeleteModel(
            name='ProgrammeAccreditation',
        ),
    ]
