# Generated by Django 5.2.3 on 2025-11-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_program_programaccreditation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(blank=True, default='under_review', max_length=15),
        ),
    ]
