# Generated by Django 5.2.3 on 2026-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_program_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_accreditation',
        ),
        migrations.AddField(
            model_name='program',
            name='applications',
            field=models.ManyToManyField(related_name='programs', to='programmes.programaccreditation'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_level',
            field=models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'Bachelors'), ('post_graduate_diploma', 'Post Graduate Diploma'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programaccreditation',
            name='program_level',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'Bachelors'), ('post_graduate_diploma', 'Post Graduate Diploma'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=100),
        ),
    ]
