# Generated by Django 5.2.3 on 2026-03-03 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_remove_program_program_accreditation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAccessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_leader', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('program_accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessors', to='programmes.programaccreditation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_accessors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
