# Generated by Django 5.2.3 on 2026-03-09 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0006_programaccessor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('program_accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='programmes.programaccreditation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_reviewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
