# Generated by Django 5.2.3 on 2026-03-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0007_programreviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programreviewer',
            old_name='program_accreditation',
            new_name='application',
        ),
    ]
