# Generated by Django 5.2.3 on 2026-03-09 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0008_rename_program_accreditation_programreviewer_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programaccreditation',
            name='preliminary_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preliminary_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
