# Generated by Django 5.2.3 on 2026-03-09 13:42

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0009_programaccreditation_preliminary_reviewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreliminaryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_entry_summary', tinymce.models.HTMLField(null=True)),
                ('type_of_entry_comments', models.TextField(blank=True, null=True)),
                ('entry_requirements_summary', tinymce.models.HTMLField(null=True)),
                ('entry_requirements_comments', models.TextField(blank=True, null=True)),
                ('human_resource_summary', tinymce.models.HTMLField(null=True)),
                ('human_resource_comments', models.TextField(blank=True, null=True)),
                ('facilities_summary', tinymce.models.HTMLField(null=True)),
                ('facilities_comments', models.TextField(blank=True, null=True)),
                ('programme_duration_summary', tinymce.models.HTMLField(null=True)),
                ('programme_duration_comments', models.TextField(blank=True, null=True)),
                ('minimum_graduation_load_summary', tinymce.models.HTMLField(null=True)),
                ('minimum_graduation_load_comments', models.TextField(blank=True, null=True)),
                ('day_students', models.PositiveIntegerField(blank=True, null=True)),
                ('evening_students', models.PositiveIntegerField(blank=True, null=True)),
                ('weekend_students', models.PositiveIntegerField(blank=True, null=True)),
                ('student_comment', models.TextField(blank=True, null=True)),
                ('expert_progression', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_reviewers', to='programmes.programaccreditation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_reviewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
