# Generated by Django 5.2.3 on 2026-03-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0010_preliminaryreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programaccreditation',
            options={'ordering': ['-date_submitted'], 'permissions': [('can_assign_reviewers', 'Can assign reviewers to applications'), ('can_assign_accessors', 'Can assign Accessors to applications')], 'verbose_name': 'Programme Accreditation Application', 'verbose_name_plural': 'Programme Accreditation Applications'},
        ),
    ]
