# Generated by Django 5.2.3 on 2026-03-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0012_alter_programaccreditation_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramReviewer',
        ),
    ]
