# Generated by Django 5.2.3 on 2026-03-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0013_delete_programreviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preliminaryreview',
            name='expert_progression',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='programaccreditation',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('progressed_to_experts', 'Progressed to Experts'), ('returned_for_review', 'Returned for Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
