# Generated by Django 5.2.3 on 2026-03-19 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0014_alter_preliminaryreview_expert_progression_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programaccreditation',
            options={'ordering': ['-date_submitted'], 'permissions': [('can_assign_reviewers', 'Can assign reviewers to applications'), ('can_assign_assessors', 'Can assign assessors to applications'), ('can_review_programme_accreditation', 'Can review programme accreditation applications'), ('can_access_programme', ' Can Access Programmes')], 'verbose_name': 'Programme Accreditation Application', 'verbose_name_plural': 'Programme Accreditation Applications'},
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
