# Generated by Django 5.2.3 on 2026-03-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0015_alter_programaccreditation_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramAccessor',
        ),
    ]
