# Generated by Django 5.2.3 on 2026-03-27 04:37

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0017_alter_programaccreditation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaccreditation',
            name='application_type',
            field=models.CharField(choices=[('new', 'New Programme'), ('renewal', 'Renewal'), ('revision', 'Revision')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='programaccreditation',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('progressed_to_experts', 'Progressed to Experts'), ('returned_for_review', 'Returned for Review'), ('under_assessment', 'Under Assessment'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
        migrations.CreateModel(
            name='ProgrammeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('programme_development_process', tinymce.models.HTMLField(null=True)),
                ('rationale', tinymce.models.HTMLField(null=True)),
                ('programme_objectives', tinymce.models.HTMLField(null=True)),
                ('competences', tinymce.models.HTMLField(null=True)),
                ('learning_outcomes', tinymce.models.HTMLField(null=True)),
                ('entry_requirements', tinymce.models.HTMLField(null=True)),
                ('duration', tinymce.models.HTMLField(null=True)),
                ('grading_system', tinymce.models.HTMLField(null=True)),
                ('curriculum_structure', tinymce.models.HTMLField(null=True)),
                ('staffing_levels', tinymce.models.HTMLField(null=True)),
                ('infrastructure', tinymce.models.HTMLField(null=True)),
                ('cbe_allignment', tinymce.models.HTMLField(null=True)),
                ('other_comments', tinymce.models.HTMLField(blank=True, null=True)),
                ('course_name', models.TextField(null=True)),
                ('course_code', models.TextField(null=True)),
                ('course_level', models.TextField(null=True)),
                ('contact_hours', models.TextField(null=True)),
                ('credit_units', models.TextField(null=True)),
                ('course_description', models.TextField(null=True)),
                ('course_objectives', models.TextField(null=True)),
                ('course_learning_outcomes', models.TextField(null=True)),
                ('detailed_course_content', models.TextField(null=True)),
                ('instructional_materials', models.TextField(null=True)),
                ('delivery_modes', models.TextField(null=True)),
                ('assessment_modes', models.TextField(null=True)),
                ('writing_styles_and_grammar', models.TextField(null=True)),
                ('minimum_standards', models.TextField(null=True)),
                ('institution_comments', models.TextField(blank=True, null=True)),
                ('nche_comments', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('accredit', 'Accredit as is'), ('minor', 'Accredit with Minor Corrections'), ('major', 'Accredit After Major Corrections'), ('reject', "Don't Accredit")], max_length=20, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_assessors', to='programmes.programaccreditation')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_assessors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
