# Generated by Django 5.2.3 on 2026-03-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0018_alter_programaccreditation_application_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmeassessment',
            options={'ordering': ['-assessment_date'], 'permissions': [('can_assess_assessments', 'Can assess programme assessments')], 'verbose_name': 'Programme Assessment', 'verbose_name_plural': 'Programme Assessments'},
        ),
        migrations.AddField(
            model_name='programmeassessment',
            name='conclusions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programmeassessment',
            name='reading_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='programaccreditation',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('progressed_to_experts', 'Progressed to Experts'), ('returned_for_review', 'Returned for Review'), ('under_assessment', 'Under Assessment'), ('progressed_to_director', 'Progressed to Director'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
