# Generated by Django 5.2.3 on 2026-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0019_alter_programmeassessment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeassessment',
            name='assessment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
