# Generated by Django 5.2.3 on 2026-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0020_alter_programmeassessment_assessment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaccreditation',
            name='pod_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
