# Generated by Django 5.2.3 on 2026-04-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0021_programaccreditation_pod_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programaccreditation',
            options={'ordering': ['-date_submitted'], 'permissions': [('can_assign_reviewers', 'Can assign reviewers to applications'), ('can_assign_assessors', 'Can assign assessors to applications'), ('can_review_programme_accreditation', 'Can review programme accreditation applications'), ('can_assess_programme', ' Can Assess Programmes'), ('can_make_directorate_decision', 'Can make decisions on programme accreditation applications')], 'verbose_name': 'Programme Accreditation Application', 'verbose_name_plural': 'Programme Accreditation Applications'},
        ),
        migrations.AlterField(
            model_name='programaccreditation',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('progressed_to_experts', 'Progressed to Experts'), ('returned_for_review', 'Returned for Review'), ('under_assessment', 'Under Assessment'), ('progressed_to_director', 'Progressed to Director'), ('return_to_assessor', 'Return to Assessor'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
