# Generated by Django 5.2.3 on 2026-04-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0022_alter_programaccreditation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programaccreditation',
            options={'ordering': ['-date_submitted'], 'permissions': [('can_assign_reviewers', 'Can assign reviewers to applications'), ('can_assign_assessors', 'Can assign assessors to applications'), ('can_review_programme_accreditation', 'Can review programme accreditation applications'), ('can_assess_programme', ' Can Assess Programmes'), ('can_make_directorate_decision', 'Can make directorate decisions on programme accreditation applications')], 'verbose_name': 'Programme Accreditation Application', 'verbose_name_plural': 'Programme Accreditation Applications'},
        ),
    ]
