# Generated by Django 5.2.3 on 2026-04-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0023_alter_programaccreditation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeassessment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_assessments', to='programmes.programaccreditation'),
        ),
    ]
