# Generated by Django 5.2.3 on 2026-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0024_alter_programmeassessment_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaccreditation',
            name='director_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='director_comment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='pod_comment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programaccreditation',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('progressed_to_experts', 'Progressed to Experts'), ('returned_for_review', 'Returned for Review'), ('under_assessment', 'Under Assessment'), ('progressed_to_director', 'Progressed to Director'), ('return_to_assessor', 'Return to Assessor'), ('progressed_to_management', 'Progressed to Management'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
