# Generated by Django 5.2.3 on 2026-04-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_alter_institution_is_closed'),
        ('programmes', '0025_programaccreditation_director_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='is_paid',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='programs', to='programmes.programaccreditation'),
        ),
    ]
