# Generated by Django 5.2.3 on 2026-04-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0026_program_institution_programaccreditation_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=250),
        ),
    ]
