# Generated by Django 5.2.3 on 2026-04-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_alter_institution_is_closed'),
        ('programmes', '0027_alter_program_program_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-accreditation_date'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('program_name', 'institution')},
        ),
    ]
