# Generated by Django 5.2.3 on 2026-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0028_alter_program_options_alter_program_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programaccreditation',
            options={'ordering': ['-date_submitted'], 'permissions': [('can_assign_reviewers', 'Can assign reviewers to applications'), ('can_assign_assessors', 'Can assign assessors to applications'), ('can_review_programme_accreditation', 'Can review programme accreditation applications'), ('can_assess_programme', ' Can Assess Programmes'), ('can_make_directorate_decision', 'Can make directorate decisions on programme accreditation applications'), ('can_manage_invoices', 'Can manage invoices for programme accreditation applications')], 'verbose_name': 'Programme Accreditation Application', 'verbose_name_plural': 'Programme Accreditation Applications'},
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='invoice_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Payment'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('under_review', 'Under Review'), ('expired', 'Expired')], default='under_review', max_length=15),
        ),
    ]
