# Generated by Django 5.2.3 on 2026-05-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0030_alter_programaccreditation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programaccreditation',
            old_name='invoice',
            new_name='invoice_file',
        ),
    ]
