# Generated by Django 5.2.3 on 2026-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0031_rename_invoice_programaccreditation_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaccreditation',
            name='invoice_cleared',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
