# Generated by Django 5.2.3 on 2026-05-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0033_alter_programaccreditation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaccreditation',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('invoice_reconciled', 'Invoice Reconciled'), ('progressed_to_experts', 'Progressed to Experts'), ('returned_for_review', 'Returned for Review'), ('under_assessment', 'Under Assessment'), ('progressed_to_accounting', 'Progressed to Accounting'), ('invoiced', 'Invoiced'), ('progressed_to_director', 'Progressed to Director'), ('return_to_assessor', 'Return to Assessor'), ('progressed_to_management', 'Progressed to Management'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
