# Generated by Django 5.2.3 on 2026-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0034_alter_programaccreditation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaccreditation',
            name='dep_meeting_minutes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
