# Generated by Django 5.2.3 on 2026-05-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0035_programaccreditation_dep_meeting_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programaccreditation',
            options={'ordering': ['-date_submitted'], 'permissions': [('can_assign_reviewers', 'Can assign reviewers to applications'), ('can_assign_assessors', 'Can assign assessors to applications'), ('can_review_programme_accreditation', 'Can review programme accreditation applications'), ('can_assess_programme', ' Can Assess Programmes'), ('can_make_directorate_decision', 'Can make directorate decisions on programme accreditation applications'), ('can_manage_invoices', 'Can manage invoices for programme accreditation applications'), ('can_approve_programme_at_management_level', 'Can approve programme at management level')], 'verbose_name': 'Programme Accreditation Application', 'verbose_name_plural': 'Programme Accreditation Applications'},
        ),
    ]
