# Generated by Django 5.2.3 on 2026-05-28 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0036_alter_programaccreditation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaccreditation',
            name='invoice_amount',
        ),
        migrations.RemoveField(
            model_name='programaccreditation',
            name='invoice_cleared',
        ),
        migrations.RemoveField(
            model_name='programaccreditation',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='programaccreditation',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='programaccreditation',
            name='invoice_payment_date',
        ),
        migrations.RemoveField(
            model_name='programaccreditation',
            name='invoice_status',
        ),
        migrations.CreateModel(
            name='ProgrammeIvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('cleared', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_invoices', to='programmes.programaccreditation')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('persons_number', models.PositiveIntegerField()),
                ('number_of_days', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='programmes.programmeivoice')),
            ],
        ),
    ]
