# Generated by Django 5.2.3 on 2026-05-28 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0037_remove_programaccreditation_invoice_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='description',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_items', to='programmes.invoiceitemtype'),
        ),
    ]
