# Generated by Django 5.2.3 on 2026-05-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0038_invoiceitemtype_remove_invoiceitem_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgrammeIvoice',
            new_name='ProgrammeInvoice',
        ),
    ]
