# Generated by Django 5.2.3 on 2026-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0039_rename_programmeivoice_programmeinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('under_review', 'Under Review'), ('due_for_review', 'Due for Review')], default='under_review', max_length=15),
        ),
    ]
