# Generated by Django 5.2.3 on 2026-05-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0040_alter_program_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaccreditation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
