# Generated by Django 5.2.3 on 2026-06-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0041_programaccreditation_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaccreditation',
            name='invoice_file',
        ),
    ]
