# Generated by Django 5.2.3 on 2026-06-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0043_alter_programaccreditation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeinvoice',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='issued', max_length=20),
        ),
    ]
