# Generated by Django 5.2.3 on 2026-06-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0044_alter_programmeinvoice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmeinvoice',
            options={'ordering': ['-invoice_date'], 'verbose_name': 'Programme Invoice', 'verbose_name_plural': 'Programme Invoices'},
        ),
        migrations.AddField(
            model_name='programmeinvoice',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='programme_invoices/'),
        ),
        migrations.AddField(
            model_name='programmeinvoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
