# Generated by Django 5.2.3 on 2026-06-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0045_alter_programmeinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeinvoice',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='issued', max_length=20),
        ),
        migrations.CreateModel(
            name='ProgrammeAssessmentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('desk_review_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('administrative_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('cleared', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='assessment_invoices/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_invoices', to='programmes.programaccreditation')),
            ],
            options={
                'verbose_name': 'Programme Assessment Invoice',
                'verbose_name_plural': 'Programme Assessment Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
