# Generated by Django 5.2.3 on 2026-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0046_alter_programmeinvoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeassessmentinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
