# Generated by Django 5.2.3 on 2026-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0047_alter_programmeassessmentinvoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programaccreditation',
            old_name='duration_semester',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='duration_type',
            field=models.CharField(choices=[('semesters', 'Semesters'), ('tri_semester', 'Tri-Semester')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programaccreditation',
            name='number_of_years',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
