# Generated by Django 5.2.3 on 2026-07-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0048_rename_duration_semester_programaccreditation_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaccreditation',
            name='duration_type',
            field=models.CharField(choices=[('semester', 'Semester'), ('tri_semester', 'Tri-Semester')], max_length=20, null=True),
        ),
    ]
