# Generated by Django 5.2.3 on 2026-07-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0049_alter_programaccreditation_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaccreditation',
            name='duration_type',
            field=models.CharField(choices=[('semester', 'Semesters'), ('tri_semester', 'Tri-Semesters')], max_length=20, null=True),
        ),
    ]
