# Generated by Django 5.2.3 on 2026-07-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0050_alter_programaccreditation_duration_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmeassessmentinvoice',
            options={'ordering': ['-invoice_date'], 'verbose_name': 'Programme Desk Review Invoice', 'verbose_name_plural': 'Programme Desk Review Invoices'},
        ),
    ]
