# Generated by Django 5.2.3 on 2026-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0051_alter_programmeassessmentinvoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaccreditation',
            name='programme_category',
            field=models.CharField(blank=True, choices=[('stem', 'STEM'), ('humanities', 'Humanities')], max_length=100, null=True),
        ),
    ]
