# Generated by Django 5.2.3 on 2026-09-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0052_programaccreditation_programme_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaccreditation',
            name='financial_implications_certificate',
            field=models.FileField(blank=True, null=True, upload_to='programmes/'),
        ),
    ]
