# Generated by Django 5.2.3 on 2026-09-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0053_programaccreditation_financial_implications_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preliminaryreview',
            name='type_of_entry_summary',
        ),
        migrations.AddField(
            model_name='preliminaryreview',
            name='type_of_entry',
            field=models.CharField(choices=[('direct', 'Direct'), ('diploma', 'Diploma'), ('mature', 'Mature'), ('heac', 'HEAC'), ('other', 'Others')], max_length=10, null=True),
        ),
    ]
