# Generated by Django 5.2.3 on 2026-09-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0054_remove_preliminaryreview_type_of_entry_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preliminaryreview',
            name='programme_duration_summary',
        ),
        migrations.AddField(
            model_name='preliminaryreview',
            name='align_with_cbet',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryreview',
            name='align_with_cbet_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryreview',
            name='programme_duration',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
