# Generated by Django 5.2.3 on 2026-09-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0055_remove_preliminaryreview_programme_duration_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminaryreview',
            name='assessment_structure',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryreview',
            name='assessment_structure_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
