# Generated by Django 5.2.3 on 2026-09-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0056_preliminaryreview_assessment_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminaryreview',
            name='tier_displine',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('applied_sciences', 'Applied Sciences'), ('pure_sciences', 'Pure Sciences'), ('business', 'Business'), ('computing', 'Computing'), ('education_arts', 'Education- Arts'), ('education_sciences', 'Education – Sciences'), ('library_studies', 'Library studies'), ('laws', 'Laws'), ('engineering', 'Engineering'), ('journalism_languages', 'Journalism and Languages'), ('social_sciences', 'Social Sciences'), ('afd', 'Art, Fashion and Design'), ('human_health', 'Human Health'), ('animal_health', 'Animal Health'), ('theology', 'Theology')], max_length=100, null=True),
        ),
    ]
