# Generated by Django 5.2.3 on 2026-09-09 00:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0057_preliminaryreview_tier_displine'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeassessment',
            name='course_competences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmeassessment',
            name='notional_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmeassessment',
            name='programme_structure',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmeassessment',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('accredit', 'Accredit as Presented'), ('minor', 'Accredit with Minor Corrections'), ('major', 'Accredit After Major Corrections'), ('reject', "Don't Accredit")], max_length=20, null=True),
        ),
    ]
