# Generated by Django 5.2.3 on 2026-09-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0058_programmeassessment_missing_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmeassessment',
            name='programme_objectives',
        ),
    ]
