# Generated by Django 5.2.3 on 2026-09-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0059_remove_programmeassessment_programme_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmeassessment',
            name='cbe_allignment',
        ),
        migrations.RemoveField(
            model_name='programmeassessment',
            name='contact_hours',
        ),
    ]
