# Generated by Django 5.2.3 on 2026-09-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0060_remove_programmeassessment_cbe_allignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmeassessment',
            name='course_objectives',
        ),
    ]
