# Generated by Django 5.2.3 on 2026-09-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0062_programaccreditation_renewal_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminaryreview',
            name='progression_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
