# Generated by Django 5.2.3 on 2025-11-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='code',
        ),
        migrations.RemoveField(
            model_name='district',
            name='code',
        ),
        migrations.RemoveField(
            model_name='historicaldistrict',
            name='code',
        ),
        migrations.RemoveField(
            model_name='parish',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='code',
        ),
        migrations.RemoveField(
            model_name='village',
            name='code',
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
