# Generated by Django 5.2.3 on 2025-11-18 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_county_code_remove_district_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='sub_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.subcounty'),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.county'),
        ),
        migrations.AlterField(
            model_name='village',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.parish'),
        ),
    ]
