# Generated by Django 5.2.3 on 2026-03-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('name', 'parish')},
        ),
    ]
