# Generated by Django 5.2.3 on 2026-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_parish_name_alter_village_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='parish',
            unique_together={('name', 'sub_county')},
        ),
        migrations.AlterUniqueTogether(
            name='subcounty',
            unique_together={('name', 'county')},
        ),
    ]
