# Generated by Django 5.2.3 on 2026-08-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_county_modified_alter_district_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeyear',
            name='current',
            field=models.BooleanField(default=False, help_text='Indicates if this is the current financial year.'),
        ),
    ]
