# Generated by Django 5.2.3 on 2025-09-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_tribe_county_parish_subcounty_village'),
        ('hr', '0002_employee_date_of_birth_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.county'),
        ),
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.district'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_Id',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.parish'),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.religion'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.subcounty'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.tribe'),
        ),
        migrations.AddField(
            model_name='employee',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.village'),
        ),
    ]
