# Generated by Django 5.2.3 on 2025-10-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_designation_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
    ]
