# Generated by Django 5.2.3 on 2025-11-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_department_name_alter_department_short_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='description',
        ),
        migrations.AddField(
            model_name='designation',
            name='code',
            field=models.CharField(default='01', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
