# Generated by Django 5.2.3 on 2025-11-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_designation_description_designation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('basic_pay', models.FloatField()),
                ('annual_leave_days', models.IntegerField()),
                ('resignation_notice_period_days', models.IntegerField()),
                ('max_advance_amount', models.FloatField()),
                ('grauity_rate', models.FloatField()),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr.designation')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
