# Generated by Django 5.2.3 on 2025-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_dependent_gender_alter_employee_system_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationhistory',
            name='certificate_document',
            field=models.FileField(null=True, upload_to='employees_documents/'),
        ),
    ]
