# Generated by Django 5.2.3 on 2025-11-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_educationhistory_certificate_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='relationship',
        ),
    ]
