# Generated by Django 5.2.3 on 2025-11-28 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_relationship'),
        ('hr', '0013_remove_dependent_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.relationship'),
        ),
    ]
