# Generated by Django 5.2.3 on 2025-12-25 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.directorate'),
        ),
    ]
