# Generated by Django 5.2.3 on 2026-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_employee_directorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
