# Generated by Django 5.2.3 on 2026-07-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_employee_office_extension_employee_office_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number'], 'permissions': [('manage_employee', 'Can manage employee')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
