# Generated by Django 5.2.3 on 2026-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow'), ('widower', 'Widower'), ('separated', 'Separated')], max_length=20, null=True),
        ),
    ]
