# Generated by Django 5.2.3 on 2026-07-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_alter_employee_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='annual_leave',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of days of annual leave for this designation', null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='basic_pay',
            field=models.FloatField(blank=True, default=0.0, help_text='Basic pay for this designation', null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='resignation_notice_period',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of days of resignation notice period for this designation', null=True),
        ),
    ]
