# Generated by Django 5.2.3 on 2026-07-29 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_county_name_alter_subcounty_name_and_more'),
        ('hr', '0020_designation_annual_leave_designation_basic_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_person_relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contact_person_relationship', to='common.relationship'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='next_of_kin_relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.relationship'),
        ),
    ]
