# Generated by Django 5.2.3 on 2026-08-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_employee_contact_person_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationhistory',
            name='certificate_document',
            field=models.FileField(blank=True, null=True, upload_to='employees_documents/'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='employees_documents/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
