# Generated by Django 5.2.3 on 2026-10-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_employee_personal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
    ]
