# Generated by Django 5.2.3 on 2026-10-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_remove_employee_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationhistory',
            name='award_date',
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='award_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
