# Generated by Django 5.2.3 on 2026-07-23 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0019_alter_employee_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('self_assessment', 'Self Assessment Submitted'), ('appraiser_review', 'Under Appraiser Review'), ('reviewer_review', 'Under Reviewer Review'), ('director_review', 'Under Director Review'), ('executive_review', 'Under Executive Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('output_total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('output_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('output_weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('competency_total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('competency_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('competency_weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_level', models.CharField(blank=True, max_length=20)),
                ('additional_tasks', models.TextField(blank=True)),
                ('skills_needed', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('supervisor_remarks', models.TextField(blank=True)),
                ('appraisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_as_appraisee', to='hr.employee')),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_as_appraiser', to='hr.employee')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_as_director', to='hr.employee')),
                ('executive_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_as_executive', to='hr.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_as_reviewer', to='hr.employee')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('start_date', 'end_date', 'appraisee')},
            },
        ),
        migrations.CreateModel(
            name='NextYearPerformancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_output', models.TextField()),
                ('performance_indicator', models.TextField()),
                ('target', models.TextField()),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_year_plans', to='appraisals.performanceappraisal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InitialQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_period', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(max_length=300)),
                ('qualification_attained', models.CharField(max_length=300)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_qualifications', to='appraisals.performanceappraisal')),
            ],
            options={
                'ordering': ['date_period'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_gap', models.TextField()),
                ('agreed_action', models.TextField()),
                ('time_frame', models.CharField(max_length=200)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_areas', to='appraisals.performanceappraisal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField()),
                ('performance_indicator', models.TextField()),
                ('performance_target', models.TextField()),
                ('self_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('appraiser_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('agreed_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='appraisals.performanceappraisal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('commenter_role', models.CharField(choices=[('appraisee', 'Appraisee'), ('appraiser', 'Appraiser'), ('reviewer', 'Reviewer'), ('director', 'Director'), ('executive', 'Executive Director')], max_length=20)),
                ('comment', models.TextField()),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appraisals.performanceappraisal')),
            ],
            options={
                'verbose_name_plural': 'Appraisal Comments',
            },
        ),
        migrations.CreateModel(
            name='AdditionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_period', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(max_length=300)),
                ('qualification_attained', models.CharField(max_length=300)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_qualifications', to='appraisals.performanceappraisal')),
            ],
            options={
                'ordering': ['date_period'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_period', models.CharField(max_length=100)),
                ('organiser', models.CharField(max_length=300)),
                ('attainment', models.CharField(max_length=500)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='appraisals.performanceappraisal')),
            ],
            options={
                'ordering': ['date_period'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_number', models.IntegerField(choices=[(1, 'Technical/Job Knowledge'), (2, 'Financial Management'), (3, 'Creativity, Personal Drive and Initiative'), (4, 'Customer Relations'), (5, 'Leadership and Motivational Ability'), (6, 'Team Work'), (7, 'Attendance and Punctuality'), (8, 'Communication'), (9, 'Integrity/Honesty'), (10, 'Confidentiality')])),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='appraisals.performanceappraisal')),
            ],
            options={
                'ordering': ['competency_number'],
                'unique_together': {('appraisal', 'competency_number')},
            },
        ),
    ]
