# Generated by Django 5.2.3 on 2026-07-30 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0001_initial'),
        ('hr', '0021_alter_employee_contact_person_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceappraisal',
            name='appraisee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_as_appraisee', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='appraiser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_as_appraiser', to='hr.employee'),
        ),
    ]
