# Generated by Django 5.2.3 on 2026-08-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0003_alter_performanceappraisal_appraisee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performanceappraisal',
            options={'ordering': ['-created'], 'permissions': (('can_approve_staff_appraisal', 'Can approve staff appraisal'), ('can_appraise_staff', 'Can appraise staff'))},
        ),
    ]
