# Generated by Django 5.2.3 on 2026-08-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0004_alter_performanceappraisal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalcomment',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
