# Generated by Django 5.2.3 on 2025-07-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_alternative_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alternative_phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
