# Generated by Django 5.2.3 on 2025-09-04 07:11

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_historicaluser_is_active_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='alternative_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UG'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UG'),
        ),
        migrations.AlterField(
            model_name='user',
            name='alternative_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UG'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UG'),
        ),
    ]
