# Generated by Django 5.2.3 on 2025-09-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_historicaluser_alternative_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='other_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
