# Generated by Django 5.2.3 on 2025-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_historicaluser_other_names_user_other_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='profile_pic',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
