# Generated by Django 5.2.3 on 2025-12-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_historicaluser_profile_pic_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
