# Generated by Django 5.2.3 on 2025-12-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_historicaluser_approved_user_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved',
        ),
    ]
