# Generated by Django 5.2.3 on 2026-08-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0015_alter_county_name_alter_subcounty_name_and_more'),
        ('hr', '0022_alter_educationhistory_certificate_document_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcurementBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_budgets', to='hr.department')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.financeyear')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='procurement.procurementitem')),
            ],
            options={
                'verbose_name_plural': 'Procurement Budgets',
                'permissions': (('can_manage_procurement_budget', 'Can manage procurement budget'),),
                'unique_together': {('item', 'fiscal_year', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('procurement_subject', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='procurement.procurementbudget')),
            ],
            options={
                'verbose_name_plural': 'Procurement Expenditures',
            },
        ),
    ]
