# Generated by Django 5.2.3 on 2026-08-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_procurementbudget_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementexpenditure',
            name='reference',
            field=models.CharField(default='exp1', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procurementexpenditure',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
