# Generated by Django 5.2.3 on 2026-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_procurementexpenditure_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementexpenditure',
            name='reference',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
