# Generated by Django 5.2.3 on 2025-07-25 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('institution_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('alternative_contact_person', models.CharField(max_length=100, null=True)),
                ('alternative_contact_person_phone', models.CharField(max_length=14, null=True)),
                ('logo', models.ImageField(null=True, upload_to='institutions/logos/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='common.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
    ]
