# Generated by Django 5.2.3 on 2025-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_person_phone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
