# Generated by Django 5.2.3 on 2025-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_institution_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
