# Generated by Django 5.2.3 on 2025-09-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_publicationyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationandclassification',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('Submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ProvisionalLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('institution_name', models.CharField(max_length=255, unique=True)),
                ('acronym', models.CharField(max_length=255, unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_licenses', to='institutions.institution')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
