# Generated by Django 5.2.3 on 2025-09-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_certificationandclassification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='post_address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CertificationAndClassification',
        ),
    ]
