# Generated by Django 5.2.3 on 2025-09-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_institution_post_address_institution_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProvisionalLicense',
        ),
    ]
