# Generated by Django 5.2.3 on 2025-09-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_institution_location_delete_provisionallicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='acroynm',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
