# Generated by Django 5.2.3 on 2025-09-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_region_historicalregion_district_region_and_more'),
        ('institutions', '0008_institution_acroynm'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='common.region'),
        ),
    ]
