# Generated by Django 5.2.3 on 2025-09-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_institution_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='post_address',
            new_name='postal_address',
        ),
    ]
