# Generated by Django 5.2.3 on 2025-12-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_rename_post_address_institution_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
