# Generated by Django 5.2.3 on 2025-12-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_licensetype_institution_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetype',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
