# Generated by Django 5.2.3 on 2026-01-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_alter_licensetype_code_alter_licensetype_name'),
        ('license', '0056_alter_certificationandclassification_library_computer_software_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationYear',
        ),
    ]
