# Generated by Django 5.2.3 on 2026-02-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_delete_publicationyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='tin',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
