# Generated by Django 5.2.3 on 2026-02-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0015_institution_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='is_closed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
