# Generated by Django 5.2.3 on 2026-08-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_alter_institution_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionvehicle',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otherdocuments',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
