# Generated by Django 5.2.3 on 2026-08-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0017_alter_institution_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='acroynm',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
