# Generated by Django 5.2.3 on 2026-08-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0018_alter_institution_acroynm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='alternative_contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/logos/'),
        ),
    ]
