# Generated by Django 5.2.3 on 2026-09-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0019_alter_institution_alternative_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='category',
            field=models.CharField(choices=[('university', 'University'), ('ODAI', 'Other Degree Awarding Institution'), ('tertiary', 'Tertiary Institution')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
