# Generated by Django 5.2.3 on 2026-10-07 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_financeyear_current'),
        ('institutions', '0020_institution_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.county'),
        ),
        migrations.AddField(
            model_name='institution',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.parish'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.subcounty'),
        ),
        migrations.AddField(
            model_name='institution',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.village'),
        ),
    ]
