# Generated by Django 5.2.3 on 2025-09-12 13:12

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_institution_location_delete_provisionallicense'),
        ('license', '0003_otiprovisional_application_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='landline',
        ),
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='website',
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='application_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='academic_board_members',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='academic_registrar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='academic_staff_computers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='administration_block_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='administrative_block_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='administrative_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='administrative_staff_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='administrative_staff_computers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='amount_of_land',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='area_for_staff_use',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='area_of_empty_space',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='area_of_playground',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='available_playgrounds',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='average_staff_student_ratio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='bachelor_holders',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='bachelor_holders_discipline',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='classroom_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='classrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='computer_labs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='computers_in_library',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='computers_in_use',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='council_members',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='cultivable_land',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='diploma_holders',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='diploma_holders_discipline',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='full_time_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='full_time_staff_qualification',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='governing_council_chairperson',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='governing_council_vice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='has_cultivable_land',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='has_internet_access',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='heads_of_academic_divisions',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='hostels_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='institution_ownership',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='intended_full_time_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='laboratories_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='land_for_future_use',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='land_in_use',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='land_owned',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='land_title',
            field=models.FileField(null=True, upload_to='land_titles/'),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='lease_or_rent_agreement',
            field=models.FileField(null=True, upload_to='land_titles/'),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='leased_or_rented',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='libraries',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='library_books',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='library_computer_software',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='library_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='master_plan',
            field=models.FileField(null=True, upload_to='land_titles/'),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='masters_holders',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='masters_holders_discipline',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='meeting_hall_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='part_time_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='part_time_staff_qualification',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='phd_holder_discipline',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='phd_holders',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='power_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='principal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='programme_staff_student_ratio',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='publication_years',
            field=models.ManyToManyField(to='institutions.publicationyear'),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='science_labs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='senate_members',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='sick_bay_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='staff_houses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='staff_houses_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='staff_overload',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='student_Welfare_offices',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='student_facilities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='students_have_access',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='support_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='text_books',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='total_roads_mileage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='water_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='years_for_future_use',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='academic_registrar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='administrative_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='administrative_staff_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='administrative_staff_computers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='classrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='council_members',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='cultivable_land',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='diploma_holders',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='diploma_holders_discipline',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='governing_council_chairperson',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='governing_council_vice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='has_cultivable_land',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='land_for_future_use',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='lease_or_rent_agreement',
            field=models.FileField(null=True, upload_to='land_titles/'),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='leased_or_rented',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='master_plan',
            field=models.FileField(null=True, upload_to='land_titles/'),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='part_time_staff_qualification',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='power_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='previous_financial_year_accounts',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='principal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='senate_members',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='staff_houses_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='support_staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='total_roads_mileage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='water_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='IntrimAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('has_title_deed', models.BooleanField()),
                ('title_deed', models.FileField(upload_to='')),
                ('names_of_promoters', tinymce.models.HTMLField(null=True)),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('objectives', models.TextField()),
                ('philosophy', models.TextField()),
                ('governance_structure', tinymce.models.HTMLField(null=True)),
                ('human_resources', tinymce.models.HTMLField(null=True)),
                ('source_of_finance', models.TextField()),
                ('action_plan', tinymce.models.HTMLField(null=True)),
                ('infrastructure', tinymce.models.HTMLField(null=True)),
                ('programmes', tinymce.models.HTMLField(null=True)),
                ('promoters', models.FileField(null=True, upload_to='')),
                ('project_proposal', models.FileField(null=True, upload_to='')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institutions.institution')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
