# Generated by Django 5.2.3 on 2025-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_remove_certificationandclassification_acronym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrimauthority',
            name='application_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='application_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
