# Generated by Django 5.2.3 on 2025-09-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_intrimauthority_application_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrimauthority',
            name='application_date',
        ),
    ]
