# Generated by Django 5.2.3 on 2025-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_remove_intrimauthority_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrimauthority',
            name='application_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
