# Generated by Django 5.2.3 on 2025-09-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_intrimauthority_application_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrimAuthorityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='intrim_authority_documents/')),
                ('intrim_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='license.intrimauthority')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
