# Generated by Django 5.2.3 on 2025-10-13 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0009_remove_certificationandclassification_staff_houses_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharterApplicationDocoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.charterapplication')),
            ],
        ),
    ]
