# Generated by Django 5.2.3 on 2025-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_charterapplicationdocoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='leased_or_rented',
            field=models.CharField(choices=[('lease', 'Lease'), ('rent', 'Rent')], max_length=10, null=True),
        ),
    ]
