# Generated by Django 5.2.3 on 2025-10-22 06:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0011_alter_universityprovisionallicense_leased_or_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='academic_staff_computers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='administration_block_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='administrative_block_area',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='administrative_staff_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='administrative_staff_computers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='agriculture_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='anual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='area_for_staff_use',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='area_of_competence',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='area_of_empty_space',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='area_of_playground',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='arts_education_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='arts_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='available_playgrounds',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='basic_sciences_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='classroom_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='classrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='computer_hardware_software',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='computer_labs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='computers_in_library',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='computers_in_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='council_members',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='cultivable_land',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='current_bankers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='detailed_programmes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='engineering_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='feature_programmes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='fee_structure',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='fees_percent_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='finance_control',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='has_cultivable_land',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='has_internet_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='heads_of_faculties',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='hostels_area',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='infrastructure_development',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='institution_ownership',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='intended_full_time_academic_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='intended_full_time_admin_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='intended_part_time_academic_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='intended_support_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='laboratories_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='libraries',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='library_books',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='library_computer_software',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='library_equipment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='library_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='master_plan',
            field=models.FileField(blank=True, null=True, upload_to='land_titles/'),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='medicine_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='meeting_hall_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='member_cvs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='other_assets',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='other_income_sources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='physical_education_facilities',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='power_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='programmes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='proposed_academic_registrar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='proposed_chancellor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='proposed_university_secretary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='proposed_vice_chancellor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='research_development',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='science_education_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='science_lab_equipment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='science_labs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='sick_bay_area',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='signatures',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='social_sciences_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='specific_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='staff_development',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='staff_houses',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='staff_salaries',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='stractegic_plan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='student_Welfare_offices',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='student_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='students_have_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='technology_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='text_books',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='total_number_of_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='total_roads_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='university_promoters',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='veterinary_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='water_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
