# Generated by Django 5.2.3 on 2025-10-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0012_alter_universityprovisionallicense_academic_staff_computers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='year_obtained',
            field=models.CharField(max_length=30),
        ),
    ]
