# Generated by Django 5.2.3 on 2025-10-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_rename_post_address_institution_postal_address'),
        ('license', '0013_alter_universityprovisionallicense_year_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='administrative_block_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='area_for_staff_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='computer_labs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='hostels_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='libraries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='publication_years',
            field=models.ManyToManyField(blank=True, to='institutions.publicationyear'),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='science_labs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='sick_bay_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='staff_houses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='student_Welfare_offices',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
