# Generated by Django 5.2.3 on 2025-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0014_alter_universityprovisionallicense_administrative_block_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='administrative_block_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='administrative_staff_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='area_for_staff_use',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='classrooms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='computer_labs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='hostels_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='libraries',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='meeting_hall_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='science_labs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='sick_bay_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='staff_houses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='student_Welfare_offices',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
