# Generated by Django 5.2.3 on 2025-10-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0015_alter_universityprovisionallicense_administrative_block_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charterapplication',
            name='area_of_playground',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='cultivable_land',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='total_roads_mileage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
