# Generated by Django 5.2.3 on 2025-10-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0016_alter_charterapplication_area_of_playground_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityprovisionallicense',
            name='number_of_vehicles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universityprovisionallicense',
            name='vehicle_registration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='cultivable_land',
            field=models.FloatField(null=True),
        ),
    ]
