# Generated by Django 5.2.3 on 2025-10-22 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0017_universityprovisionallicense_number_of_vehicles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityprovisionallicense',
            name='publication_years',
        ),
        migrations.AddField(
            model_name='universityprovisionallicense',
            name='publication_years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, default=list, size=None),
        ),
    ]
