# Generated by Django 5.2.3 on 2025-10-22 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0018_remove_universityprovisionallicense_publication_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='library_computer_software',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='publication_years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, default=list, size=None),
        ),
    ]
