# Generated by Django 5.2.3 on 2025-10-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0019_alter_universityprovisionallicense_library_computer_software_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='other_assets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
