# Generated by Django 5.2.3 on 2025-10-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0020_alter_universityprovisionallicense_other_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='finance_control',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
