# Generated by Django 5.2.3 on 2025-10-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0021_alter_universityprovisionallicense_finance_control'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityprovisionallicense',
            old_name='anual_budget',
            new_name='annual_budget',
        ),
    ]
