# Generated by Django 5.2.3 on 2025-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0022_rename_anual_budget_universityprovisionallicense_annual_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='annual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=250, null=True),
        ),
    ]
