# Generated by Django 5.2.3 on 2025-10-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0023_alter_universityprovisionallicense_annual_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityprovisionallicense',
            name='location',
        ),
    ]
