# Generated by Django 5.2.3 on 2025-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0024_remove_universityprovisionallicense_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charterapplication',
            name='location',
        ),
        migrations.AddField(
            model_name='charterapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
