# Generated by Django 5.2.3 on 2025-10-31 07:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0025_remove_charterapplication_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterapplication',
            name='provisional_license_issue_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='charterapplication',
            name='publication_years',
        ),
        migrations.AddField(
            model_name='charterapplication',
            name='publication_years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, default=list, size=None),
        ),
    ]
