# Generated by Django 5.2.3 on 2025-10-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0026_charterapplication_provisional_license_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charterapplication',
            name='year_obtained',
            field=models.CharField(max_length=30),
        ),
    ]
