# Generated by Django 5.2.3 on 2025-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0027_alter_charterapplication_year_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationandclassification',
            name='leased_or_rented',
            field=models.CharField(choices=[('lease', 'Lease'), ('rent', 'Rent')], max_length=10, null=True),
        ),
    ]
