# Generated by Django 5.2.3 on 2025-10-31 13:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0028_alter_certificationandclassification_leased_or_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='leased_or_rented',
        ),
        migrations.RemoveField(
            model_name='charterapplication',
            name='leased_or_rented',
        ),
        migrations.RemoveField(
            model_name='otiprovisional',
            name='leased_or_rented',
        ),
        migrations.RemoveField(
            model_name='universityprovisionallicense',
            name='leased_or_rented',
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='lease_or_rent_agreement',
            field=models.FileField(blank=True, null=True, upload_to='land_titles/'),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='academic_registrar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='academic_staff_computers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='administration_block_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='administrative_block_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='administrative_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='administrative_staff_computers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='agriculture_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='annual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='area_for_staff_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='area_of_empty_space',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='area_of_playground',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='areadministrative_staff_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='areas_of_competence',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='arts_education_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='arts_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='available_playgrounds',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='average_staff_student_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='bachelor_holders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='bachelor_holders_discipline',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='basic_science_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='central_region',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='chancellor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='classroom_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='classrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='computer_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='computer_labs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='computers_in_library',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='computers_in_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='council_members',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='cultivable_land',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='current_bankers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='deans',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='detailed_programmes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='diploma_holders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='diploma_holders_discipline',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='east_africans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='eastern_region',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='engineering_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='facilities',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='fees_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='fees_structure',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='financial_control',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='full_time_academic_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='has_cultivable_land',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='has_internet_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='hostels_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='infrastructure_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='intended_full_time_academic_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='intended_part_time_academic_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='laboratories_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='lease_or_rent_agreement',
            field=models.FileField(blank=True, null=True, upload_to='land_titles/'),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='libraries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='library_books',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='library_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='library_computer_software',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='library_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='master_plan',
            field=models.FileField(blank=True, null=True, upload_to='land_titles/'),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='masters_holders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='masters_holders_discipline',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='medicine_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='meeting_hall_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='northern_region',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='other_assets',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='other_income_source',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='other_regions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='other_students_numbers',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='ownership',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='phd_holder_discipline',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='phd_holders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='power_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='previous_year_accounts',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='programme_staff_student_ratio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='programmes_offered',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='research_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='science_labs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='science_labs_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='senate_members',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='sick_bay_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='signature_officers',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='social_science_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='specific_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='staff_development_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='staff_houses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='staff_overload',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='staff_salary_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='student_Welfare_offices',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='student_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='students_have_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='support_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='text_books',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='total_roads_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='total_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='university_secretary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='university_strategic_plan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='veterinary_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='vice_chancellor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='vice_registrar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='water_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charterapplication',
            name='western_region',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
