# Generated by Django 5.2.3 on 2025-10-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0029_remove_certificationandclassification_leased_or_rented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationandclassification',
            name='leased_or_rented',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='charterapplication',
            name='leased_or_rented',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='leased_or_rented',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='universityprovisionallicense',
            name='leased_or_rented',
            field=models.BooleanField(null=True),
        ),
    ]
