# Generated by Django 5.2.3 on 2025-12-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0030_certificationandclassification_leased_or_rented_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseType',
        ),
    ]
