# Generated by Django 5.2.3 on 2025-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0031_delete_licensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrimauthority',
            name='admin_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='certificate_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='certificate_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='council_decision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='fee_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='fee_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='preliminary_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='vetting_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intrimauthority',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('prelim_review', 'Under Preliminary Review'), ('prelim_feedback', 'Preliminary Feedback Issued'), ('vetting_scheduled', 'Scheduled for Vetting'), ('vetting_in_progress', 'Vetting in Progress'), ('vetting_feedback', 'Vetting Decision Issued'), ('admin_visit_pending', 'Administrative Visit Pending'), ('admin_visit_done', 'Administrative Visit Completed'), ('under_directorate_review', 'Under Directorate Review'), ('under_management_review', 'Under Management Review'), ('under_qaac_review', 'Under QAAC Review'), ('under_council_review', 'Under Council Review'), ('approved_pending_fees', 'Approved – Pending Fee Payment'), ('fees_invoiced', 'Fees Invoiced'), ('fees_paid', 'Fees Paid – Certificate Processing'), ('certificate_ready', 'Certificate Ready for Collection'), ('completed', 'Completed – LIA Issued'), ('on_hold_requirements', 'On Hold – Requirements Not Met'), ('on_hold_non_compliance', 'On Hold – Non-Compliance Issues'), ('deferred', 'Deferred'), ('rejected', 'Rejected / Not Approved')], default='draft', max_length=50),
        ),
    ]
