# Generated by Django 5.2.3 on 2025-12-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0032_intrimauthority_admin_visit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprovisionallicense',
            name='leased_or_rented',
            field=models.CharField(choices=[('lease', 'Lease'), ('rent', 'Rent')], max_length=20, null=True),
        ),
    ]
