# Generated by Django 5.2.3 on 2025-12-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0034_interimdiscussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interimdiscussion',
            old_name='intrim_authority',
            new_name='application',
        ),
    ]
