# Generated by Django 5.2.3 on 2025-12-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0035_rename_intrim_authority_interimdiscussion_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interimdiscussion',
            old_name='content',
            new_name='text',
        ),
    ]
