# Generated by Django 5.2.3 on 2026-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0039_alter_otiprovisional_administrative_block_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otiprovisional',
            name='leased_or_rented',
            field=models.CharField(choices=[('lease', 'Lease'), ('rent', 'Rent')], max_length=20, null=True),
        ),
    ]
