# Generated by Django 5.2.3 on 2026-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0040_alter_otiprovisional_leased_or_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otiprovisional',
            name='land_owned',
        ),
        migrations.RemoveField(
            model_name='otiprovisional',
            name='years_for_future_use',
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='land_acquisition_years',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
