# Generated by Django 5.2.3 on 2026-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_alter_licensetype_code_alter_licensetype_name'),
        ('license', '0041_remove_otiprovisional_land_owned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otiprovisional',
            name='publication_years',
            field=models.ManyToManyField(blank=True, to='institutions.publicationyear'),
        ),
    ]
