# Generated by Django 5.2.3 on 2026-01-14 07:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0042_alter_otiprovisional_publication_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otiprovisional',
            name='library_computer_software',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.RemoveField(
            model_name='otiprovisional',
            name='publication_years',
        ),
        migrations.AddField(
            model_name='otiprovisional',
            name='publication_years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, default=list, size=None),
        ),
    ]
