# Generated by Django 5.2.3 on 2026-01-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0043_alter_otiprovisional_library_computer_software_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otiprovisional',
            name='bachelor_holders_discipline',
        ),
        migrations.RemoveField(
            model_name='otiprovisional',
            name='diploma_holders_discipline',
        ),
        migrations.AlterField(
            model_name='otiprovisional',
            name='average_staff_student_ratio',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otiprovisional',
            name='staff_overload',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
