# Generated by Django 5.2.3 on 2026-01-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0044_remove_otiprovisional_bachelor_holders_discipline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otiprovisional',
            name='senate_members',
        ),
    ]
