# Generated by Django 5.2.3 on 2026-01-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0045_remove_otiprovisional_senate_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otiprovisional',
            name='previous_financial_year_accounts',
        ),
    ]
