# Generated by Django 5.2.3 on 2026-01-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0046_remove_otiprovisional_previous_financial_year_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otiprovisional',
            name='feature_programmes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
