# Generated by Django 5.2.3 on 2026-01-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0047_alter_otiprovisional_feature_programmes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otiprovisional',
            name='logo',
        ),
    ]
