# Generated by Django 5.2.3 on 2026-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0048_remove_otiprovisional_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='otiprovisional',
            name='financial_control_mechanism',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
