# Generated by Django 5.2.3 on 2026-01-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0050_alter_certificationandclassification_academic_staff_computers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='provisional_license_issue_date',
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='OTIProvisionalAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('award_letter', models.FileField(upload_to='oti_provisional_awards/')),
                ('issue_date', models.DateField()),
                ('oti_provisional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='license.otiprovisional')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='provisional_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='license.otiprovisionalaward'),
        ),
    ]
