# Generated by Django 5.2.3 on 2026-01-19 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_alter_licensetype_code_alter_licensetype_name'),
        ('license', '0051_remove_certificationandclassification_provisional_license_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otiprovisionalaward',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otiprovisionalaward',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='otiprovisionalaward',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institutions.institution'),
        ),
    ]
