# Generated by Django 5.2.3 on 2026-01-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0052_otiprovisionalaward_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationandclassification',
            name='leased_or_rented',
            field=models.CharField(choices=[('lease', 'Lease'), ('rent', 'Rent')], max_length=20, null=True),
        ),
    ]
