# Generated by Django 5.2.3 on 2026-01-19 13:38

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_alter_licensetype_code_alter_licensetype_name'),
        ('license', '0053_alter_certificationandclassification_leased_or_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationandclassification',
            name='academic_board_members',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='academic_registrar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='academic_staff_computers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='administration_block_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='administrative_block_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='administrative_staff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='administrative_staff_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='administrative_staff_computers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='anual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='area_for_staff_use',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='area_of_competence',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='area_of_empty_space',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='area_of_playground',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='available_playgrounds',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='average_staff_student_ratio',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='bachelor_holders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='bachelor_holders_discipline',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='central_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='classroom_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='classrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='computer_hardware_software',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='computer_labs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='computers_in_library',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='computers_in_use',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='council_members',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='cultivable_land',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='current_bankers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='current_programmes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='diploma_holders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='diploma_holders_discipline',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='east_africans_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='eastern_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='feature_programmes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='fee_structure',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='fees_percent_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='full_time_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='full_time_staff_qualification',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='governing_council_chairperson',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='governing_council_vice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='has_cultivable_land',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='has_internet_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='heads_of_academic_divisions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='hostels_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='infrastructure_development',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='institution_ownership',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='intended_full_time_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='laboratories_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='libraries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='library_books',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='library_computer_software',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='library_equipment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='library_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='master_plan',
            field=models.FileField(blank=True, null=True, upload_to='land_titles/'),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='masters_holders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='masters_holders_discipline',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='meeting_hall_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='northern_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='other_assets',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='other_institution_income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='other_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='part_time_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='part_time_staff_qualification',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='phd_holder_discipline',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='phd_holders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='power_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='previous_financial_year_accounts',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='principal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='programme_distribution',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='programme_staff_student_ratio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='publication_years',
            field=models.ManyToManyField(blank=True, to='institutions.publicationyear'),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='research_development',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='science_lab_equipment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='science_labs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='senate_members',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='sick_bay_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='specific_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='staff_development',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='staff_houses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='staff_overload',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='staff_salaries',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='stractegic_plan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='student_Welfare_offices',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='student_facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='students_have_access',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='support_staff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='text_books',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='total_number_of_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='total_roads_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='water_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='western_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
