# Generated by Django 5.2.3 on 2026-01-19 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_alter_licensetype_code_alter_licensetype_name'),
        ('license', '0054_alter_certificationandclassification_academic_board_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationandclassification',
            name='institution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='institutions.institution'),
        ),
    ]
