# Generated by Django 5.2.3 on 2026-01-22 08:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0055_alter_certificationandclassification_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationandclassification',
            name='library_computer_software',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='publication_years',
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='publication_years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, default=list, size=None),
        ),
    ]
