# Generated by Django 5.2.3 on 2026-01-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0056_alter_certificationandclassification_library_computer_software_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificationandclassification',
            old_name='anual_budget',
            new_name='annual_budget',
        ),
    ]
