# Generated by Django 5.2.3 on 2026-01-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0057_rename_anual_budget_certificationandclassification_annual_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationandclassification',
            name='current_programmes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificationandclassification',
            name='feature_programmes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
