# Generated by Django 5.2.3 on 2026-01-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0058_alter_certificationandclassification_current_programmes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationandclassification',
            name='programme_distribution',
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='agriculture_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='arts_education_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='arts_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='basic_sciences_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='engineering_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='medicine_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='science_education_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='social_sciences_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='veterinary_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
