# Generated by Django 5.2.3 on 2026-01-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0059_remove_certificationandclassification_programme_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationandclassification',
            name='detailed_programmes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='financial_control_mechanism',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='members_cvs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='physical_education_facilities',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='certificationandclassification',
            name='signatures',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
