# Generated by Django 5.2.3 on 2026-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0060_certificationandclassification_detailed_programmes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provisionallicenseodia',
            name='institution',
        ),
        migrations.AddField(
            model_name='charterapplication',
            name='is_odi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='is_odi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universityprovisionallicense',
            name='is_odi',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CharterApplicationODI',
        ),
        migrations.DeleteModel(
            name='ProvisionalLicenseODIA',
        ),
    ]
