# Generated by Django 5.2.3 on 2026-01-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0061_remove_provisionallicenseodia_institution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charterapplication',
            old_name='is_odi',
            new_name='is_odia',
        ),
        migrations.RenameField(
            model_name='intrimauthority',
            old_name='is_odi',
            new_name='is_odia',
        ),
        migrations.RenameField(
            model_name='universityprovisionallicense',
            old_name='is_odi',
            new_name='is_odia',
        ),
    ]
