# Generated by Django 5.2.3 on 2026-01-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0062_rename_is_odi_charterapplication_is_odia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charterapplication',
            old_name='is_odia',
            new_name='is_odai',
        ),
        migrations.RenameField(
            model_name='intrimauthority',
            old_name='is_odia',
            new_name='is_odai',
        ),
        migrations.RenameField(
            model_name='universityprovisionallicense',
            old_name='is_odia',
            new_name='is_odai',
        ),
    ]
