# Generated by Django 5.2.3 on 2026-02-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0063_rename_is_odia_charterapplication_is_odai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterapplication',
            name='number_of_vehicles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charterapplication',
            name='vehicle_registration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
