# Generated by Django 5.2.3 on 2026-02-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0064_charterapplication_number_of_vehicles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charterapplication',
            old_name='areadministrative_staff_area',
            new_name='administrative_staff_area',
        ),
        migrations.RenameField(
            model_name='charterapplication',
            old_name='student_Welfare_offices',
            new_name='student_welfare_offices',
        ),
    ]
