# Generated by Django 5.2.3 on 2026-02-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0065_rename_areadministrative_staff_area_charterapplication_administrative_staff_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charterapplication',
            name='library_computer_software',
            field=models.TextField(blank=True, null=True),
        ),
    ]
