# Generated by Django 5.2.3 on 2026-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0066_alter_charterapplication_library_computer_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterapplication',
            name='part_time_academic_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
