# Generated by Django 5.2.3 on 2026-02-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0067_charterapplication_part_time_academic_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charterapplication',
            name='intended_part_time_academic_staff',
        ),
    ]
