# Generated by Django 5.2.3 on 2026-02-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0068_remove_charterapplication_intended_part_time_academic_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charterapplication',
            name='average_staff_student_ratio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
