# Generated by Django 5.2.3 on 2026-02-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0069_alter_charterapplication_average_staff_student_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterapplication',
            name='science_education_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
