# Generated by Django 5.2.3 on 2026-02-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0070_charterapplication_science_education_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterapplication',
            name='member_cvs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
