# Generated by Django 5.2.3 on 2026-02-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0071_charterapplication_member_cvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otiprovisional',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
