# Generated by Django 5.2.3 on 2026-02-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0073_alter_certificationandclassification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charterapplication',
            name='leased_or_rented',
            field=models.CharField(choices=[('lease', 'Lease'), ('rent', 'Rent')], max_length=20, null=True),
        ),
    ]
