# Generated by Django 5.2.3 on 2026-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0074_alter_charterapplication_leased_or_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='charterapplication',
            name='application_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
