# Generated by Django 5.2.3 on 2026-04-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0076_alter_charterapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intrimauthority',
            options={'permissions': [('can_review_application', 'Can review application')]},
        ),
        migrations.AlterField(
            model_name='otiprovisional',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
