# Generated by Django 5.2.3 on 2026-04-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0077_alter_intrimauthority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intrimauthority',
            options={'permissions': [('can_review_application', 'Can review application'), ('can_assign_interim_authority_reviewer', 'Can assign interim authority reviewer')]},
        ),
    ]
