# Generated by Django 5.2.3 on 2026-04-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0078_alter_intrimauthority_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intrimauthority',
            name='desk_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desk_review_interim_authorities', to=settings.AUTH_USER_MODEL),
        ),
    ]
