# Generated by Django 5.2.3 on 2026-06-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0079_intrimauthority_desk_reviewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityprovisionallicense',
            options={'permissions': [('can_review_application', 'Can review application'), ('can_assign_university_provisional_reviewer', 'Can assign university provisional reviewer')]},
        ),
    ]
