# Generated by Django 5.2.3 on 2026-06-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0080_alter_universityprovisionallicense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityprovisionallicense',
            options={'permissions': [('can_review_provisional_license_application', 'Can review provisional license application'), ('can_assign_university_provisional_reviewer', 'Can assign university provisional reviewer')]},
        ),
    ]
