# Generated by Django 5.2.3 on 2026-06-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0081_alter_universityprovisionallicense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charterapplication',
            options={'permissions': [('can_review_charter_application', 'Can review charter application'), ('can_assign_charter_reviewer', 'Can assign charter reviewer')]},
        ),
    ]
