# Generated by Django 5.2.3 on 2026-08-10 08:58

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0083_alter_certificationandclassification_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrimauthority',
            name='geographical_location',
            field=models.CharField(choices=[('urban', 'Urban'), ('rural', 'Rural')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='intrimauthority',
            name='land_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='InterimPromoters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('application', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='license.intrimauthority')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
