# Generated by Django 5.2.3 on 2026-08-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0084_intrimauthority_geographical_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrimauthority',
            name='names_of_promoters',
        ),
    ]
