# Generated by Django 5.2.3 on 2026-09-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0086_intrimauthorityobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrimauthorityobjective',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='intrimauthorityobjective',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='intrimauthorityobjective',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
