# Generated by Django 5.2.3 on 2026-09-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0087_intrimauthorityobjective_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrimauthority',
            name='objectives',
        ),
    ]
