# Generated by Django 5.2.3 on 2026-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0088_remove_intrimauthority_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrimauthority',
            name='governance_structure',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
