# Generated by Django 5.2.3 on 2026-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0089_alter_intrimauthority_governance_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrimauthority',
            name='human_resources',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
