# Generated by Django 5.2.3 on 2026-10-07 07:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0090_alter_intrimauthority_human_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrimauthority',
            name='infrastructure',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
